# Perfil de produccion (despliegue)

# Nombre del proyecto
spring.application.name=Udipsai

# Puerto del servidor
server.port=${SERVER_PORT:8080}

# Configuraciï¿½n de JDBC (Base de datos)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate (Crea y actualiza las tablas de la base de datos)
# Se usa auto update solo en este perfil
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configuracion de JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging
logging.level.root=${LOG_LEVEL:INFO}
logging.level.ec.ucacue=${APP_LOG_LEVEL:INFO}

# Swagger
spring.data.rest.detection-strategy=annotated